<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.simple.common</groupId>
    <artifactId>simple-common</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>simple-common</name>

    <modules>
        <module>simple-common-core</module>
        <module>simple-common-redis</module>
        <module>simple-common-rabbitmq</module>
        <module>simple-common-eventbus</module>
        <module>simple-common-annex</module>
        <module>simple-common-mp</module>
        <module>simple-common-doc</module>
        <module>simple-common-excel</module>
        <module>simple-common-logs</module>
        <module>simple-common-xxljob</module>
        <module>simple-common-sms</module>
        <module>simple-common-auth</module>
        <module>simple-common-test</module>
        <module>simple-common-websocket</module>
        <module>simple-common-cache</module>
        <module>simple-common-alibaba</module>
        <module>simple-common-ai</module>
        <module>simple-common-oauth</module>
    </modules>

<!--    <distributionManagement>-->
<!--        <repository>-->
<!--            <id>maven-releases</id>-->
<!--            <name>Releases Repository</name>-->
<!--            <url>http://nexus.dev.joyswon.com/repository/maven-releases/</url>-->
<!--        </repository>-->
<!--    </distributionManagement>-->

    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven-surefire-plugin.version>2.12.4</maven-surefire-plugin.version>
        <maven-release-plugin.versinon>3.0.0-M7</maven-release-plugin.versinon>
        <spring-boot-maven-plugin.versinon>3.1.0</spring-boot-maven-plugin.versinon>
        <spring-boot.version>3.3.4</spring-boot.version>
        <spring-clould-alibaba>2023.0.3.4</spring-clould-alibaba>
        <spring-cloud.version>2023.0.3</spring-cloud.version>
        <common.simple.version>1.0.0</common.simple.version>

        <hutool.version>5.8.38</hutool.version>
        <aviator.version>5.4.3</aviator.version>
        <jbcrypt.version>0.4</jbcrypt.version>
        <net.version>3.11.1</net.version>
        <knife4j.versinon>4.5.0</knife4j.versinon>
        <knife4j.spring-webmvc.version>6.1.14</knife4j.spring-webmvc.version>
        <redisson.version>3.36.0</redisson.version>
        <amazonaws.version>1.12.594</amazonaws.version>
        <minio.version>8.5.10</minio.version>
        <aliyun.version>3.10.2</aliyun.version>
        <mp.versinon>3.5.9</mp.versinon>
        <easy.excel.version>4.0.3</easy.excel.version>
        <poi.tl.version>1.12.2</poi.tl.version>
        <poi.version>5.2.3</poi.version>
        <xxl.job.version>2.4.1</xxl.job.version>
        <sdk-core.version>4.7.6</sdk-core.version>
        <dysmsapi20170525.version>4.1.2</dysmsapi20170525.version>
        <tea.version>1.3.1</tea.version>
        <jjwt.version>0.12.6</jjwt.version>
        <jbcrypt.version>0.4</jbcrypt.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <zxing.version>3.5.3</zxing.version>
        <fastjson2.version>2.0.61</fastjson2.version>
        <dashscope.version>2.22.12</dashscope.version>
        <bcprov.version>1.70</bcprov.version>
        <netty.version>4.1.100.Final</netty.version>
        <protobuf.version>3.24.0</protobuf.version>
        <commons-io.version>2.15.1</commons-io.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- 引入 Spring Cloud BOM -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-clould-alibaba}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-bom</artifactId>
                <version>${mp.versinon}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--aws s3-->
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>${amazonaws.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun.oss</groupId>
                <artifactId>aliyun-sdk-oss</artifactId>
                <version>${aliyun.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mindrot</groupId>
                <artifactId>jbcrypt</artifactId>
                <version>${jbcrypt.version}</version>
            </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <dependency>
                <groupId>com.googlecode.aviator</groupId>
                <artifactId>aviator</artifactId>
                <version>${aviator.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-net</groupId>
                <artifactId>commons-net</artifactId>
                <version>${net.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>${knife4j.versinon}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-webmvc</artifactId>
                <version>${knife4j.spring-webmvc.version}</version>
            </dependency>

            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson</artifactId>
                <version>${redisson.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>${poi.version}</version>
            </dependency>

            <dependency>
                <groupId>com.deepoove</groupId>
                <artifactId>poi-tl</artifactId>
                <version>${poi.tl.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>${easy.excel.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>aliyun-java-sdk-core</artifactId>
                <version>${sdk-core.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>dysmsapi20170525</artifactId>
                <version>${dysmsapi20170525.version}</version>
            </dependency>

            <dependency>
                <groupId>com.aliyun</groupId>
                <artifactId>tea</artifactId>
                <version>${tea.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            <dependency>
                <groupId>com.xuxueli</groupId>
                <artifactId>xxl-job-core</artifactId>
                <version>${xxl.job.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.zxing</groupId>
                <artifactId>core</artifactId>
                <version>${zxing.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.zxing</groupId>
                <artifactId>javase</artifactId>
                <version>${zxing.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>dashscope-sdk-java</artifactId>
                <version>${dashscope.version}</version>
            </dependency>

            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcpkix-jdk15on</artifactId>
                <version>${bcprov.version}</version>
            </dependency>

            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${netty.version}</version>
            </dependency>

            <!-- commons-io 解决 POI 5.2.3 兼容性问题 -->
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-core</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-redis</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-rabbitmq</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-eventbus</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-annex</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-mp</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-doc</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-excel</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-logs-server</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-logs-client</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-auth-client</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-auth-server</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-xxljob</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-sms</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-cache</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-alibaba</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-ai</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-websocket</artifactId>
                <version>${common.simple.version}</version>
            </dependency>

            <dependency>
                <groupId>com.simple.common</groupId>
                <artifactId>simple-common-logs-proto</artifactId>
                <version>${common.simple.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.7.1</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>${maven-release-plugin.versinon}</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <parameters>true</parameters>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${spring-boot-maven-plugin.versinon}</version>
                <configuration>
                    <nonFilteredFileExtensions>
                        <!--过滤不转换的格式，这里主要是防止资源文件夹下的文件在编译后无法打开的问题-->
                        <nonFilteredFileExtension>xls</nonFilteredFileExtension>
                        <nonFilteredFileExtension>xlsx</nonFilteredFileExtension>
                        <nonFilteredFileExtension>docx</nonFilteredFileExtension>
                        <nonFilteredFileExtension>doc</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                    <outputDirectory/>
                </configuration>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <!-- 启用过滤 即该资源中的变量将会被过滤器中的值替换 -->
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <profiles>
        <profile>
            <id>local</id>
            <properties>
                <spring.active>local</spring.active>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>

        <profile>
            <id>dev</id>
            <properties>
                <spring.active>dev</spring.active>
            </properties>
        </profile>

        <profile>
            <id>test</id>
            <properties>
                <spring.active>test</spring.active>
            </properties>
        </profile>

        <profile>
            <id>produce</id>
            <properties>
                <spring.active>produce</spring.active>
            </properties>
        </profile>
    </profiles>
</project>
