<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.simple.common</groupId>
        <artifactId>simple-common</artifactId>
        <version>1.0.1</version>
    </parent>

    <artifactId>simple-common-sms</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>aliyun-java-sdk-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-mp</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-redis</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>dysmsapi20170525</artifactId>
        </dependency>

        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>tea</artifactId>
        </dependency>

    </dependencies>

</project>