<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.simple.common</groupId>
        <artifactId>simple-common</artifactId>
        <version>1.0.1</version>
    </parent>

    <artifactId>simple-common-test</artifactId>
    <packaging>jar</packaging>

    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-cache</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-eventbus</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-annex</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-excel</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-mp</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-ai</artifactId>
        </dependency>

        <dependency>
            <groupId>com.simple.common</groupId>
            <artifactId>simple-common-websocket</artifactId>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>com.simple.common</groupId>-->
<!--            <artifactId>simple-common-logs-server</artifactId>-->
<!--        </dependency>-->

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- web 容器使用 undertow -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>

    </dependencies>
</project>
