export JAVA_HOME=/etc/graalvm-ce-java17-22.3.1
export JAVA_OPTS="-Xms4g -Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:ParallelGCThreads=2 -XX:ConcGCThreads=1 -Dio.netty.leakDetectionLevel=disabled"
