server:
  port: 8001
#  tomcat:
#    accept-count: 100 # 等待队列，当可分配的线程数全部用完之后，后续的请求将进入等待队列等待，等待队列满后则拒绝处理，默认100
#    max-connections: 10000 # 最大可连接数，默认10000，超出后出现拒绝链接的情况
#    threads:
#      max: 200 # 最大工作线程数，默认200
#      min-spare: 10 # 最小工作线程数，初始化分配线程数，默认10
#  # undertow 配置
#  undertow:
#    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
#    max-http-post-size: -1
#    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
#    # 每块buffer的空间大小,越小的空间被利用越充分
#    buffer-size: 512
#    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
#    threads:
#      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
#      io: 8
#      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
#      worker: 256
#
#    # 是否分配的直接内存
#    direct-buffers: true
spring:
  application:
    name: common-test
  profiles:
    active: @spring.active@
  threads:
    virtual:
      enabled: true # 虚拟线程，需要jdk21或者以上。
  # entity时间类型数据格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 数据库返回时间格式化
    time-zone: GMT+8 # 时区设置

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://develop.dev.joyswon.com:5432/simple-${spring.application.name}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: postgres
    password: 123456
    hikari:
      auto-commit: true # 自动提交
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      idle-timeout: 30000 # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      maxLifeTime: 600000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      maximum-pool-size: 100 # 连接池中允许的最大连接数。缺省值：10
      minimum-idle: 10 # 最小连接数
  data:
    redis:
      database: 1
      host: develop.dev.joyswon.com
      port: 6379
      password: 12345678
      timeout: 3s
      lettuce.pool:
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 10 # 连接池中的最小空闲连接
        max-active: 100 # 连接池的最大数据库连接数。设为0表示无限制。一般设置为并发量
        max-wait: 3000 # 从连接池中获取连接的最大等待时间（毫秒）
  rabbitmq:
    addresses: develop.dev.joyswon.com:5672
    username: admin
    password: Abc$123456789
    listener:
      simple:
        acknowledge-mode: MANUAL # 确认模式：MANUAL-手动ack，AUTO-自动ack，失败需要手动抛出异常，NONE-没有ack
        prefetch: 1 # 未确认消息的最大数量，也叫作分发模式：0-轮训，每台服务器一次循环，1-公平分发，是服务器压力进行分发，> 1：预取数据的数量-适当增大可以提升消费速度
        default-requeue-rejected: false # 消费失败的q是否重新放回队列重新消费
        # concurrency: 1 # 消费线程数
        # max-concurrency: 10 # 消费线程最大数量
# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml # mapper扫描路径
  configuration:
    auto-mapping-behavior: full # MyBatis 自动映射策略：none-不启用自动映射，partial-只对非嵌套的 resultMap 进行自动映射，full-对所有的 resultMap 都进行自动映射
    auto-mapping-unknown-column-behavior: warning # MyBatis 自动映射时未知列或未知属性处理策略：none-不做任何处理 (默认值)，warning-日志打印出来，failing-当作映射失败处理，并抛出异常和详细信息
    cache-enabled: false # mybatis二级缓存
    call-setters-on-nulls: false # 指定当结果集中值为 null 的时候是否调用映射对象的 Setter（Map 对象时为 put）方法，通常运用于有 Map.keySet() 依赖或 null 值初始化的情况。

    # Mybatis一级缓存，单服务架构中（有且仅有只有一个程序提供相同服务），一级缓存开启不会影响业务，只会提高性能。
    # 微服务架构中需要关闭一级缓存，原因：Service1先查询数据，若之后Service2修改了数据，之后Service1又再次以同样的查询条件查询数据，因走缓存会出现查处的数据不是最新数据
    # session-session级别缓存，同一个session相同查询语句不会再次查询数据库，statement-关闭一级缓存
    local-cache-scope: statement
    map-underscore-to-camel-case: true # 下划线自动驼峰转化，如果您的数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
  global-config:
    banner: false # 控制台MP logo是否显示
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
# doc文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '测试服务'
      paths-to-match: '/**'
      packages-to-scan: com.simple.common.test.controller

simple:
  annex: # 附件上传配置
    server-url: http://develop.dev.joyswon.com:9000
    access-key: admin
    access-secret: Abc$123456789
    expire-time: 30
    algorithm: md5